problem:
  version: 0.4
  shape:
    name: "Transformer2"
    dimensions: [ B, M, E, D ]

    data_spaces:
    - name: I
      projection:
      - [ [B] ]
      - [ [M] ]
      - [ [D] ]
    - name: WQ
      projection:
      - [ [D] ]
      - [ [E] ]
    - name: Q
      projection:
      - [ [B] ]
      - [ [M] ]
      - [ [E] ]
      read_write: True

  instance: