mapping:
  type: fused
  nodes:
  - type: storage
    target: 0  # level 0 is bound to global DRAM
    dspace: [I, WK, K, WQ, Q, QK, WV, V, AV, Z, WZ] #-------- node 2.a
  - type: temporal
    rank: B6
    tile_shape: 6
  - type: storage
    target: 1  # level 1 is bound to DRAM
    dspace: [WK, K, WQ, Q, QK, WV, V, AV, WZ]
  - type: sequential  #------------------------------- node 2.d
    branches:
    - - type: temporal
        rank: M1
        tile_shape: 1024
      - type: spatial
        rank: M1
        tile_shape: 1
      - type: temporal
        rank: E1
        tile_shape: 1
      - type: temporal
        rank: D1
        tile_shape: 1
      - type: compute
        einsum: KeyProjection
        target: 2  # level 3 is bound to MACC
    - - type: temporal
        rank: M2
        tile_shape: 1024
      - type: spatial
        rank: M2
        tile_shape: 1
      - type: temporal
        rank: E2
        tile_shape: 1
      - type: temporal
        rank: D2
        tile_shape: 1
      - type: compute
        einsum: QueryProjection
        target: 2  # level 3 is bound to MACC
    - - type: temporal
        rank: M3
        tile_shape: 1024
      - type: spatial
        rank: M3
        tile_shape: 1
      - type: temporal
        rank: P3
        tile_shape: 1  
      - type: temporal
        rank: E3
        tile_shape: 1  
      - type: compute
        einsum: QueryKeyMult
        target: 2  # level 3 is bound to MACC
    - - type: temporal
        rank: M4
        tile_shape: 1024
      - type: spatial
        rank: M4
        tile_shape: 1
      - type: temporal
        rank: F4
        tile_shape: 1 
      - type: temporal
        rank: D4
        tile_shape: 1  
      - type: compute
        einsum: ValueProjection
        target: 2  # level 3 is bound to MACC
    - - type: temporal
        rank: M5
        tile_shape: 1024
      - type: spatial
        rank: M5
        tile_shape: 1
      - type: temporal
        rank: P5
        tile_shape: 1  
      - type: temporal
        rank: F5
        tile_shape: 1  
      - type: compute
        einsum: AttentionValue
        target: 2  # level 3 is bound to MACC
    - - type: temporal
        rank: P6
        tile_shape: 1024
      - type: spatial
        rank: P6
        tile_shape: 1
      - type: temporal
        rank: F6
        tile_shape: 1 
      - type: temporal
        rank: G6
        tile_shape: 1  
      - type: compute
        einsum: Output
        target: 2  # level 3 is bound to MACC