architecture:
  version: 0.4
  nodes:
  # Top-level node representing a single Rack
    - !Container
      name: rack
      attributes: # Apply to rack scope unless overridden
        technology: "45nm"
        global_cycle_seconds: 1e-9
        datawidth: 16
        width: 256

    # Rack-level shared DRAM
    - !Component
      name: MainMemory
      class: DRAM
      attributes:
        width: 256
        depth: 16384000000      # Number of entries (approx 16.4G)
                                # Total size: (1024b * 16.4G) / 8 = ~2 TiB
        datawidth: 16
      required_actions: ['read', 'write']
   
    - !Container
      name: PE
      spatial: {meshX: 4}
      attributes: # Apply to rack scope unless overridden
        width: 256
        datawidth: 16

    - !Component
      name: GlobalBuffer
      class: DRAM
      attributes:
        width: 256
        depth: 512000000
        datawidth: 16
      required_actions: ['read', 'write']
    
    - !Container
      name: block
      spatial: {meshX: 1024}
      attributes: # Apply to rack scope unless overridden
        width: 256
        datawidth: 16
    
    - !Container
      name: thread
      spatial: {meshX: 32}
      attributes: # Apply to rack scope unless overridden
        width: 256
        datawidth: 16
    
    - !Component
      name: thread_reg
      class: regfile
      attributes:
        depth: 16
        width: 16
        datawidth: 16
      required_actions: ['read', 'write']
    
    - !Component
      name: MACC
      class: intmac
      attributes:
        num_pipeline_stages: 1
        datawidth: 16
        width: 64
        cycle_time: 1e-9
      required_actions: ['compute']