architecture:
  version: 0.4
  nodes:
  # Top-level node representing a single Rack
  - !Container
    name: rack
    attributes: # Apply to rack scope unless overridden
      technology: "45nm"
      global_cycle_seconds: 1e-9 # 1 GHz clock
      datawidth: 16             # Default data bus width
    components:
    # Rack-level shared DRAM
    - !Component
      name: global_DRAM
      class: DRAM
      attributes:
        width: 1024             # Bits accessed in parallel
        depth: 16384000000      # Number of entries (approx 16.4G)
                                # Total size: (1024b * 16.4G) / 8 = ~2 TiB
        datawidth: datawidth    # Inherited (16 bits)

    # Container for the PEs (GPUs) within the rack
    - !Container
      name: PE # Processing Element (GPU)
      spatial: {meshX: 4, meshY: 16} # 4x16 grid = 64 PEs per rack
      components:
      # GPU's local DRAM
      - !Component
        name: DRAM
        class: DRAM
        attributes:
          width: 256              # Bits accessed in parallel
          depth: 512000000        # Number of entries (512M)
                                  # Total size: (256b * 512M) / 8 = 16 GiB
          datawidth: datawidth    # Inherited (16 bits)

      # Container for Blocks within each PE (GPU)
      - !Container
        name: block
        spatial: {meshX: 512}     # 512 Blocks per PE (GPU)
        components:

        # Container for Threads within each Block
        - !Container
          name: thread
          spatial: {meshX: 1024}  # 1024 Threads per Block
          components:
          # Register file per Thread
          - !Component
            name: thread_reg
            class: reg_storage    # Or 'regfile'
            attributes:
              depth: 16           # Number of registers
              width: 16           # Width of each register in bits
              datawidth: datawidth # Inherited (16 bits)

          # MAC unit per Thread
          - !Component
            name: mac
            class: mac_compute    # Or 'intmac'/'fpmac'
            attributes:
              num_pipeline_stages: 2
              datawidth: datawidth # Inherited (16 bits)