architecture:
  version: 0.4
  nodes:
  # Top-level node representing a single Rack
  - !Hierarchical
    name: rack
    attributes: # Apply to rack scope unless overridden
      technology: "45nm"
      global_cycle_seconds: 1e-9 # 1 GHz clock
      datawidth: 16             # Default data bus width
    nodes:
    # Rack-level shared DRAM
    - !Component
      name: global_DRAM
      class: DRAM
      attributes:
        width: 256             # Bits accessed in parallel
        depth: 1024 # 16384000000      # Number of entries (approx 16.4G)
                                # Total size: (1024b * 16.4G) / 8 = ~2 TiB
        datawidth: datawidth    # Inherited (16 bits)

    - !Container
      name: PE
      spatial: {meshX: 16}
    
      - !Component
        name: GPU_DRAM
        class: DRAM
        attributes:
          width: 256
          depth: 512
          datawidth: datawidth
    
      - !Container
        name: block
        spatial: {meshX: 64}
    
        - !Container
          name: thread
          spatial: {meshX: 32}
    
          - !Component
            name: thread_reg
            class: reg_storage
            attributes:
              depth: 16
              width: 16
              datawidth: datawidth
    
          - !Component
            name: mac
            class: mac_compute
            attributes:
              num_pipeline_stages: 2
              datawidth: datawidth