architecture:
  version: 0.4
  nodes:
  - !Container
    name: rack
    spatial: {meshX: {{4}}, meshY: {{16}}}
    attributes: unless overridden
      technology: "45nm"
      global_cycle_seconds: 1e-9
      datawidth: 16

  - !Component
    name: global_DRAM  # global rack DRAM
    class: DRAM
    attributes:
      width: 1024
      datawidth: 16
      depth: 16384000000

  - !Container
    name: PE # this is each GPU
    spatial: {meshX: {{4}}, meshY: {{16}}}

  - !Component
    name: DRAM  # global GPU DRAM
    class: DRAM
    attributes:
      width: 256
      datawidth: 16
      depth: 512000000

  - !Container
    name: block
    spatial: {meshX: {{512}}} # 2 dimensional

  # threads for the block
  - !Container
    name: thread
    spatial: {meshX: {{1024}}}

  # registers for each thread
  - !Component
    name: thread_reg
    class: reg_storage
    attributes: {depth: 16, width: 16, datawidth: 16}

  - !Component
    name: mac
    class: mac_compute
    attributes: {num_pipline_stages: 2, datawidth: 16}