problem:
    - shape:
        name: KeyProjection
        dimensions: [ B1, M1, E1, D1 ]
        data_spaces:
        - name: I
          dimensions: [I_B, I_M, I_D]
          projection: '[ B1, M1, D1 ]'
        - name: WK
          dimensions: [WK_D, WK_E]
          projection: '[ D1, E1 ]'
        - name: K
          dimensions: [K_B, K_M, K_E]
          projection: '[ B1, M1, E1 ]'
          read_write: True
    
      instance: >-
        0 <= B1 < 16 and 0 <= M1 < 512 and 0 <= E1 < 128 and 0 <= D1 < 128

    - shape:
        name: QueryProjection
        dimensions: [ B2, M2, E2, D2 ]
    
        data_spaces:
        - name: I
          dimensions: [I_B, I_M, I_D]
          projection: '[ B2, M2, D2 ]'
        - name: WQ
          dimensions: [WQ_D, WQ_E]
          projection: '[ D2, E2 ]'
        - name: Q
          dimensions: [Q_B, Q_M, Q_E]
          projection: '[ B2, M2, E2 ]'
          read_write: True

      instance: >-
        0 <= B2 < 16 and 0 <= M2 < 512 and 0 <= E2 < 128 and 0 <= D2 < 128

    - shape:
        name: QueryKeyMult
        dimensions: [ B3, M3, P3, E3 ]
    
        data_spaces:
        - name: Q
          dimensions: [Q_B, Q_M, Q_E]
          projection: '[ B3, M3, E3 ]'
          read_write: True
        - name: K
          dimensions: [K_B, K_M, K_E]
          projection: '[ B3, M3, E3 ]'
          read_write: True
        - name: QK
          dimensions: [QK_B, QK_M, QK_P]
          projection: '[ B3, M3, P3 ]'
          read_write: True
    
      instance: >-
        0 <= B3 < 16 and 0 <= M3 < 512 and 0 <= E3 < 128 and 0 <= P3 < 512

    - shape:
        name: ValueProjection
        dimensions: [ B4, M4, F4, D4 ]
    
        data_spaces:
        - name: I
          dimensions: [I_B, I_M, I_D]
          projection: '[ B4, M4, D4 ]'
        - name: WV
          dimensions: [WV_D, WV_F]
          projection: '[D4, F4]'
        - name: V
          dimensions: [V_B, V_M, V_F]
          projection: '[B4, M4, F4]'
          read_write: True
    
      instance: >-
        0 <= B4 < 16 and 0 <= M4 < 512 and 0 <= F4 < 128 and 0 <= D4 < 128

    # - shape:
    #     name: AttentionValue
    #     dimensions: [ B5, M5, P5, F5 ]
    
    #     data_spaces:
    #     - - name: QK
    #       dimensions: [QK_B, QK_M, QK_P]
    #       projection: '[ B5, M5, P5 ]'
    #     - name: V
    #       dimensions: [V_B, V_M, V_F]
    #       projection: '[B5, M5, F5]'
    #     - name: AV
    #       dimensions: [AV_B, AV_P, AV_F]
    #       projection: '[B5, P5, F5]'
    #       read_write: True
    
    #   instance: >-
    #     0 <= B5 < 16 and 0 <= M5 < 512 and 0 <= F5 < 128 and 0 <= P5 < 512

    # - shape:
    #     name: Output
    #     dimensions: [ B6, P6, F6, G6 ]
    
    #     data_spaces:
    #     - name: AV
    #       dimensions: [AV_B, AV_P, AV_F]
    #       projection: '[B6, P6, F6]'
    #     - name: WZ
    #       dimensions: [WZ_F, WZ_G]
    #       projection: '[F6, G6]'
    #     - name: Z
    #       dimensions: [Z_B, Z_P, Z_G]
    #       projection: '[B6, P6, G6]'
    #       read_write: True
    
    #   instance: >-
    #     0 <= B6 < 16 and 0 <= P6 < 512 and 0 <= F6 < 128 and 0 <= G6 < 128