variables:
  global_cycle_seconds: 1e-9
  technology: "45nm"

architecture:
  version: 0.4
  nodes:
  - !Component
    name: MainMemory
    class: DRAM
    attributes: {depth: 100000000000, width: 256, block_size: 32, word_bits: 8, datawidth: 8}
    required_actions: ['read', 'write']
  - !Container
    name: PE
    attributes:
        datawidth: 8
        width: 256
  - !Component
    name: GlobalBuffer
    class: SRAM
    attributes:
        depth: 81920
        width: 256
        block_size: 32
        word_bits: 8
        datawidth: 8
        n_rdwr_ports: 2
        n_rd_ports: 0
        n_wr_ports: 0
    required_actions: ['read', 'write']
  - !Component
    name: MACC
    class: intmac
    attributes:
        datawidth: 16
        width: 16
        cycle_time: 1e-9
    required_actions: ['compute']