architecture:
  version: 0.4
  nodes:
  # Top-level node representing a single Rack
    - !Container
      name: rack
      attributes: # Apply to rack scope unless overridden
        technology: "45nm"
        global_cycle_seconds: 1e-9 # 1 GHz clock
        datawidth: 16             # Default data bus width
        width: 256

    # Rack-level shared DRAM
    - !Component
      name: global_DRAM
      class: DRAM
      attributes:
        width: 256             # Bits accessed in parallel
        depth: 1024 # 16384000000      # Number of entries (approx 16.4G)
                                # Total size: (1024b * 16.4G) / 8 = ~2 TiB
        datawidth: 16    # Inherited (16 bits)
   
    - !Container
      name: PE
      spatial: {meshX: 16}
      attributes: # Apply to rack scope unless overridden
        width: 256
        datawidth: 16

    - !Component
      name: GPU_DRAM
      class: DRAM
      attributes:
        width: 256
        depth: 512
        datawidth: 16
    
    - !Container
      name: block
      spatial: {meshX: 64}
      attributes: # Apply to rack scope unless overridden
        width: 256
        datawidth: 16
    
    - !Container
      name: thread
      spatial: {meshX: 32}
      attributes: # Apply to rack scope unless overridden
        width: 256
        datawidth: 16
    
    - !Component
      name: thread_reg
      class: DRAM
      attributes:
        depth: 16
        width: 256
        datawidth: 16
    
    - !Component
      name: MACC
      class: intmac
      attributes:
        datawidth: 32
        width: 16
        cycle_time: 1e-9
      required_actions: ['compute']